class AppStrings {
  final String languageCode;

  const AppStrings(this.languageCode);

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Work Solute Cooperative',
      'coop_union': 'Cooperative Union',
      'municipal_network': 'Public Home Services Platform · Local Cooperative Network',
      'select_language': 'Select your language',
      'select_language_subtitle': 'Choose your preferred language for service booking, verified technician updates, and fair-rate invoices.',
      'welcome_title': 'Welcome to Work Solute',
      'welcome_sub': 'Book trusted, verified cooperative workers near you with fair pricing and zero broker markups.',
      'continue_google': 'Continue with Google',
      'or_use_email': 'Or use email',
      'email_label': 'Email Address',
      'password_label': 'Password',
      'remember_device': 'Remember this device',
      'forgot_password': 'Forgot password?',
      'sign_in': 'Sign In',
      'create_account': 'Create new account',
      'member_guarantee_title': 'Member Protection Guarantee',
      'member_guarantee_desc': 'No broker commission markups. Standard transparent rates set by verified municipal guild councils. Background-checked local technicians.',
      'verify_phone_title': 'Verify your phone number',
      'verify_phone_desc': 'We use this to send job updates, coordinate arrival, and share your secure job-start OTP with your cooperative technician.',
      'enter_otp': 'Enter 6-digit verification code',
      'resend_otp_in': 'Resend OTP in',
      'resend_sms': 'Resend SMS',
      'whatsapp_otp': 'Get OTP via WhatsApp',
      'verify_continue': 'Verify & Continue',
      'change_phone': 'Change phone number',
      'zero_spam_title': '🔒 Zero Spam & Data Protection',
      'zero_spam_desc': 'Your phone number is strictly masked when communicating with workers. It will serve as your canonical contact for doorstep OTP job starts.',
      'home_nav': 'Home',
      'bookings_nav': 'My Bookings',
      'profile_nav': 'Profile',
      'verified_workers_badge': 'Verified cooperative workers',
      'trust_hero_title': 'Book trusted cooperative workers',
      'trust_hero_sub': 'Fair wages, verified credentials, and cooperative-owned home services in your ward.',
      'members_online': '142 Members Online',
      'avg_rating': '4.92 / 5 avg rating',
      'emergency_title': 'Need help urgently?',
      'emergency_sub': 'Electrical short, burst pipe, sudden lockouts',
      'emergency_btn': 'Request Emergency Service',
      'coop_services': 'Co-op Services',
      'fair_rates': 'Fair Rates',
      'trades_active': '8 Trades Active',
      'search_placeholder': 'Search service or problem (e.g. tap, fan)',
      'why_sahayak': 'Why Work Solute Cooperative?',
      'step1_title': 'Describe your issue',
      'step1_sub': 'Clear descriptions help our cooperative plumbers bring the exact copper fittings and seals.',
      'service_type': 'Service type',
      'add_photos': 'Add photos or video',
      'step2_title': 'Time & Location',
      'asap_option': 'As soon as possible',
      'schedule_option': 'Schedule for later',
      'select_date': 'Select Date',
      'available_slots': 'Available Slots',
      'service_location': 'Service Location',
      'fair_match_guarantee': 'Work Solute Fair Match Guarantee',
      'continue_to_matching': 'Continue to Worker Match',
      'available_workers': 'Available workers for your job',
      'how_recommended': 'How workers are recommended',
      'booking_confirmed': 'Booking Confirmed',
      'job_otp_label': 'Job Start Security OTP',
      'service_progress': 'Service Progress Tracker',
      'call_tech': 'Call',
      'chat_tech': 'In-App Chat',
      'my_profile_title': 'My Profile & Settings',
      'profile_sub': 'Manage credentials, addresses & preferences',
      'saved_addresses': 'Saved Addresses',
      'app_language': 'App Language',
      'notification_prefs': 'Notification Preferences',
      'civic_guarantee': 'Co-op Civic Guarantee & Safety',
      'help_support': 'Help & Support',
      'log_out': 'Log Out of Account',
      'choose_mode': 'Choose Service Mode',
      'choose_mode_sub': 'Instant dispatch or scheduled pro',
      'emergency_request': 'Emergency Request',
      'emergency_sub_short': 'Urgent repairs, immediate help',
      'book_service': 'Book a Service',
      'book_sub_short': 'Scheduled appointments, verified workers',
      'emergency_domains': '🚨 Emergency Domains',
      'service_domains': '📅 Service Domains',
      'view_all': 'View All',
      'hello': 'Hello',
      'my_bookings': 'My Bookings',
      'bookings_sub': 'Guaranteed household services',
      'tab_upcoming': 'Upcoming',
      'tab_completed': 'Completed',
      'tab_cancelled': 'Cancelled',
      'no_upcoming_bookings': 'No upcoming bookings',
      'no_completed_bookings': 'No completed bookings',
      'no_cancelled_bookings': 'No cancelled bookings',
      'verify_otp_action': 'Doorstep OTP',
      'complete_pay_action': 'Pay & Complete',
      'cancel_booking_action': 'Cancel',
      'view_details': 'View Details',
      'book_a_service_now': 'Book a Service Now',
      'stat_bookings': 'Bookings',
      'stat_completed': 'Completed',
      'stat_addresses': 'Addresses',
      'verified_citizen': 'Verified Citizen',
      'primary_contact': 'Primary Doorstep Contact',
      'invoicing_email': 'Electronic Invoicing',
      'verified_label': 'Verified',
      'verified_otp': 'Verified OTP',
      'add_address': 'Add',
      'default_badge': 'Default',
      'set_default': 'Set as Default',
      'whatsapp_updates': 'WhatsApp Dispatch Updates',
      'whatsapp_sub': 'Real-time technician route alerts',
      'sms_otp': 'SMS Job-Start OTP',
      'sms_sub': 'Secure one-time pin for doorstep start',
      'booking_reminders': 'Booking Reminders',
      'reminders_sub': 'Reminders 1 hour prior to visit',
      'support_helpline': '24/7 Support Helpline',
      'faqs': 'Frequently Asked Questions (FAQs)',
      'faqs_sub': 'Cooperative booking guidelines & policy',
      'edit_profile': 'Edit Profile',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'neighborhood': 'Neighborhood',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'confirm_logout': 'Log Out of Account?',
      'logout_confirm_msg': 'Are you sure you want to sign out?',
      'detect_live_gps': 'Detect Live Device GPS',
      'detect_live_gps_sub': 'Uses real-time device sensor coordinates',
      'service_location_title': 'Service Location',
      'current_location_label': 'Current Location (Live GPS)',
      'rapid_dispatch_badge': 'Rapid dispatch available (<20 min)',
      'zero_commission_title': 'Zero-Commission Charter',
      'zero_commission_sub': '100% labor earnings go directly to workers',
      'guild_standards_title': 'Worker Guild Standards',
      'guild_standards_sub': 'Background checks & trade testing',
      'insurance_title': 'Insurance Protection Coverage',
      'insurance_sub': 'Covered up to ₹25,000 for incidental safety',
      'app_version_label': 'Work Solute Cooperative App v2.4.1',
      'app_footer_desc': 'Public Digital Good · Cooperative Platform',
      'worker_set_price': 'Fair rate set by worker',
      'no_base_price': 'Worker custom quote',
      'otp_verification_title': 'OTP Verification',
      'sms_sent_to': 'SMS code sent to',
      'step_security': 'Step 2 of 2 · Account Security',
      'mobile_number': 'Mobile Number',
      'otp_sms_sent_desc': 'An OTP has been sent via SMS to this number.',
      'secure_pin': 'Secure PIN',
      'worker_quote': 'Worker Quote',
    },
    'ta': {
      'app_title': 'Work Solute கூட்டுறவு',
      'coop_union': 'கூட்டுறவு சங்கம்',
      'municipal_network': 'உள்ளூர் கூட்டுறவு நெட்வொர்க் · பொது தளம்',
      'select_language': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'select_language_subtitle': 'சேவை முன்பதிவு, சரிபார்க்கப்பட்ட தொழிலாளர் தகவல்கள் மற்றும் நியாயமான கட்டணங்களுக்கான மொழியைத் தேர்வுசெய்யவும்.',
      'welcome_title': 'Work Solute-க்கு வரவேற்கிறோம்',
      'welcome_sub': 'தரகர் கட்டணமின்றி, நியாயமான விலையில் சரிபார்க்கப்பட்ட உள்ளூர் கூட்டுறவு தொழிலாளர்களை முன்பதிவு செய்யுங்கள்.',
      'continue_google': 'Google மூலம் தொடரவும்',
      'or_use_email': 'அல்லது மின்னஞ்சல் மூலம்',
      'email_label': 'மின்னஞ்சல் முகவரி',
      'password_label': 'கடவுச்சொல்',
      'remember_device': 'சாதனத்தை நினைவில் கொள்க',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'sign_in': 'உள்நுழைக',
      'create_account': 'புதிய கணக்கை உருவாக்கவும்',
      'member_guarantee_title': 'உறுப்பினர் பாதுகாப்பு உத்தரவாதம்',
      'member_guarantee_desc': 'தரகர் கமிஷன் இல்லை. கூட்டுறவு சங்கம் நிர்ணயித்த வெளிப்படையான கட்டணங்கள். போலீஸ் சரிபார்க்கப்பட்ட உள்ளூர் தொழிலாளர்கள்.',
      'verify_phone_title': 'தொலைபேசி எண்ணை சரிபார்க்கவும்',
      'verify_phone_desc': 'வேலை விவரங்கள் மற்றும் கதவு பாதுகாப்பு OTP அனுப்ப இந்த எண் பயன்படுகிறது.',
      'enter_otp': '6 இலக்க OTP குறியீட்டை உள்ளிடவும்',
      'resend_otp_in': 'மறுஅனுப்பீடு நேரம்',
      'resend_sms': 'SMS மீண்டும் அனுப்புக',
      'whatsapp_otp': 'WhatsApp மூலம் OTP பெறுக',
      'verify_continue': 'சரிபார்த்து தொடரவும்',
      'change_phone': 'எண்ணை மாற்றவும்',
      'zero_spam_title': '🔒 பூஜ்ஜிய ஸ்பேம் & தரவு பாதுகாப்பு',
      'zero_spam_desc': 'தொழிலாளர்களுடன் பேசும்போது உங்கள் எண் மறைக்கப்படும்.',
      'home_nav': 'முகப்பு',
      'bookings_nav': 'முன்பதிவுகள்',
      'profile_nav': 'சுயவிவரம்',
      'verified_workers_badge': 'சரிபார்க்கப்பட்ட கூட்டுறவு தொழிலாளர்கள்',
      'trust_hero_title': 'நம்பகமான கூட்டுறவு தொழிலாளர்களை முன்பதிவு செய்க',
      'trust_hero_sub': 'நியாயமான ஊதியம், சரிபார்க்கப்பட்ட சான்றுகள் மற்றும் உங்கள் பகுதியில் கூட்டுறவு சேவைகள்.',
      'members_online': '142 தொழிலாளர்கள் தயார்',
      'avg_rating': '4.92 / 5 சராசரி மதிப்பீடு',
      'emergency_title': 'அவசர உதவி தேவையா?',
      'emergency_sub': 'மின் கசிவு, குழாய் வெடிப்பு, திடீர் கதவு பூட்டு',
      'emergency_btn': 'அவசர சேவை கோரிக்கை',
      'coop_services': 'கூட்டுறவு சேவைகள்',
      'fair_rates': 'நியாயமான கட்டணம்',
      'trades_active': '8 துறைகள் செயலில்',
      'search_placeholder': 'சேவை அல்லது சிக்கலைத் தேடுங்கள் (எ.கா. குழாய், மின்விசிறி)',
      'why_sahayak': 'ஏன் Work Solute கூட்டுறவு?',
      'step1_title': 'உங்கள் சிக்கலை விளக்குங்கள்',
      'step1_sub': 'தெளிவான விளக்கம் சரியான உதிரிபாகங்களுடன் வர உதவுகிறது.',
      'service_type': 'சேவை வகை',
      'add_photos': 'புகைப்படம் அல்லது வீடியோ சேர்க்கவும்',
      'step2_title': 'நேரம் மற்றும் இருப்பிடம்',
      'asap_option': 'விரைவில் (அவசர சேவை)',
      'schedule_option': 'பின்னர் திட்டமிடுங்கள்',
      'select_date': 'தேதியைத் தேர்ந்தெடுக்கவும்',
      'available_slots': 'கிடைக்கும் நேரங்கள்',
      'service_location': 'சேவை இடம்',
      'fair_match_guarantee': 'Work Solute நியாயமான ஒதுக்கீடு',
      'continue_to_matching': 'தொழிலாளர் பொருத்தத்திற்கு செல்க',
      'available_workers': 'உங்கள் வேலைக்கு கிடைக்கும் தொழிலாளர்கள்',
      'how_recommended': 'தொழிலாளர்கள் எவ்வாறு பரிந்துரைக்கப்படுகிறார்கள்',
      'booking_confirmed': 'முன்பதிவு உறுதி செய்யப்பட்டது',
      'job_otp_label': 'வேலை தொடக்க பாதுகாப்பு OTP',
      'service_progress': 'சேவை முன்னேற்றக் கண்காணிப்பு',
      'call_tech': 'அழைக்க',
      'chat_tech': 'செயலி சாட்',
      'my_profile_title': 'எனது சுயவிவரம் & அமைப்புகள்',
      'profile_sub': 'சான்றுகள், முகவரிகள் & விருப்பங்கள்',
      'saved_addresses': 'சேமிக்கப்பட்ட முகவரிகள்',
      'app_language': 'செயலி மொழி',
      'notification_prefs': 'அறிவிப்பு அமைப்புகள்',
      'civic_guarantee': 'கூட்டுறவு பாதுகாப்பு & உத்தரவாதம்',
      'help_support': 'உதவி & ஆதரவு',
      'log_out': 'வெளியேறவும்',
      'choose_mode': 'சேவை முறையைத் தேர்ந்தெடுக்கவும்',
      'choose_mode_sub': 'உடனடி அனுப்பீடு அல்லது திட்டமிடப்பட்ட சேவை',
      'emergency_request': 'அவசர கோரிக்கை',
      'emergency_sub_short': 'அவசர பழுது, உடனடி உதவி',
      'book_service': 'சேவையை முன்பதிவு செய்',
      'book_sub_short': 'திட்டமிடப்பட்ட நேரம், சரிபார்க்கப்பட்ட தொழிலாளர்',
      'emergency_domains': '🚨 அவசர துறைகள்',
      'service_domains': '📅 சேவை துறைகள்',
      'view_all': 'அனைத்தும் பார்',
      'hello': 'வணக்கம்',
      'my_bookings': 'எனது முன்பதிவுகள்',
      'bookings_sub': 'உத்தரவாதமுள்ள வீட்டு சேவைகள்',
      'tab_upcoming': 'வரவிருக்கும்',
      'tab_completed': 'முடிந்தவை',
      'tab_cancelled': 'ரத்து செய்யப்பட்டவை',
      'no_upcoming_bookings': 'வரவிருக்கும் முன்பதிவுகள் இல்லை',
      'no_completed_bookings': 'முடிந்த முன்பதிவுகள் இல்லை',
      'no_cancelled_bookings': 'ரத்து செய்யப்பட்ட முன்பதிவுகள் இல்லை',
      'verify_otp_action': 'பாதுகாப்பு OTP',
      'complete_pay_action': 'பணம் செலுத்து',
      'cancel_booking_action': 'ரத்து செய்',
      'view_details': 'விவரங்களை பார்க்க',
      'book_a_service_now': 'இப்போது முன்பதிவு செய்',
      'stat_bookings': 'முன்பதிவுகள்',
      'stat_completed': 'முடிந்தவை',
      'stat_addresses': 'முகவரிகள்',
      'verified_citizen': 'சரிபார்க்கப்பட்ட பயனர்',
      'primary_contact': 'முதன்மை தொடர்பு எண்',
      'invoicing_email': 'மின்னணு ரசீது',
      'verified_label': 'சரிபார்க்கப்பட்டது',
      'verified_otp': 'சரிபார்க்கப்பட்ட OTP',
      'add_address': 'சேர்க்க',
      'default_badge': 'முதன்மை',
      'set_default': 'முதன்மை ஆக்கு',
      'whatsapp_updates': 'WhatsApp அறிவிப்புகள்',
      'whatsapp_sub': 'தொழிலாளர் வருகை எச்சரிக்கைகள்',
      'sms_otp': 'SMS வேலை தொடக்க OTP',
      'sms_sub': 'கதவு தொடக்கத்திற்கான பாதுகாப்பு பின்',
      'booking_reminders': 'முன்பதிவு நினைவூட்டல்கள்',
      'reminders_sub': 'சேவைக்கு 1 மணி நேரம் முன்',
      'support_helpline': '24/7 உதவி எண்',
      'faqs': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'faqs_sub': 'கூட்டுறவு முன்பதிவு வழிகாட்டுதல்கள்',
      'edit_profile': 'சுயவிவரம் திருத்து',
      'full_name': 'முழு பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'neighborhood': 'பகுதி / குடியிருப்பு',
      'save_changes': 'சேமிக்க',
      'cancel': 'ரத்து',
      'confirm_logout': 'வெளியேறவா?',
      'logout_confirm_msg': 'நிச்சயமாக கணக்கிலிருந்து வெளியேற விரும்புகிறீர்களா?',
      'detect_live_gps': 'நேரடி GPS இருப்பிடத்தைக் கண்டறி',
      'detect_live_gps_sub': 'சாதன சென்சார் இருப்பிடத்தைப் பயன்படுத்துகிறது',
      'service_location_title': 'சேவை இடம்',
      'current_location_label': 'தற்போதைய இடம் (Live GPS)',
      'rapid_dispatch_badge': 'விரைவு அனுப்பீடு (<20 நிமிடம்)',
      'zero_commission_title': 'பூஜ்ஜிய கமிஷன் சட்டம்',
      'zero_commission_sub': '100% வருவாய் தொழிலாளர்களுக்கு நேரில் செல்கிறது',
      'guild_standards_title': 'தொழிலாளர் சங்கம் தரநிலைகள்',
      'guild_standards_sub': 'பின்னணி சரிபார்ப்பு மற்றும் தகுதித் தேர்வு',
      'insurance_title': 'பாதுகாப்பு காப்பீடு',
      'insurance_sub': '₹25,000 வரை பாதுகாப்பு காப்பீடு வழங்கப்படுகிறது',
      'app_version_label': 'Work Solute கூட்டுறவு செயலி v2.4.1',
      'app_footer_desc': 'பொது தளம் · உள்ளூர் கூட்டுறவு நெட்வொர்க்',
      'worker_set_price': 'தொழிலாளர் நிர்ணயித்த கட்டணம்',
      'no_base_price': 'தொழிலாளர் விலைப்புள்ளி',
      'otp_verification_title': 'OTP சரிபார்ப்பு',
      'sms_sent_to': 'SMS குறியீடு அனுப்பப்பட்டது:',
      'step_security': 'படி 2 / 2 · கணக்கு பாதுகாப்பு',
      'mobile_number': 'கைபேசி எண்',
      'otp_sms_sent_desc': 'இந்த எண்ணுக்கு SMS மூலம் OTP அனுப்பப்பட்டுள்ளது.',
      'secure_pin': 'பாதுகாப்பான பின்',
      'worker_quote': 'தொழிலாளர் விலைப்புள்ளி',
    },
    'hi': {
      'app_title': 'Work Solute को-ऑपरेटिव',
      'coop_union': 'सहकारी संघ',
      'municipal_network': 'स्थानीय सहकारी नेटवर्क · सार्वजनिक मंच',
      'select_language': 'अपनी भाषा चुनें',
      'select_language_subtitle': 'सेवा बुकिंग, प्रमाणित कारीगरों और पारदर्शी दरों के लिए अपनी पसंदीदा भाषा चुनें।',
      'welcome_title': 'Work Solute में आपका स्वागत है',
      'welcome_sub': 'बिना किसी बिचौलिए कमीशन के अपने नजदीकी प्रमाणित सहकारी कारीगरों को बुक करें।',
      'continue_google': 'Google के साथ जारी रखें',
      'or_use_email': 'या ईमेल का उपयोग करें',
      'email_label': 'ईमेल पता',
      'password_label': 'पासवर्ड',
      'remember_device': 'इस डिवाइस को याद रखें',
      'forgot_password': 'पासवर्ड भूल गए?',
      'sign_in': 'साइन इन करें',
      'create_account': 'नया खाता बनाएं',
      'member_guarantee_title': 'सदस्य सुरक्षा गारंटी',
      'member_guarantee_desc': 'शून्य दलाल कमीशन। सहकारी गिल्ड द्वारा तय पारदर्शी दरें। पुलिस सत्यापित कारीगर।',
      'verify_phone_title': 'अपना फ़ोन नंबर सत्यापित करें',
      'verify_phone_desc': 'हम इसका उपयोग कार्य अपडेट भेजने और डोरस्टेप ओटीपी साझा करने के लिए करते हैं।',
      'enter_otp': '6 अंकों का ओटीपी कोड दर्ज करें',
      'resend_otp_in': 'ओटीपी पुनः भेजें',
      'resend_sms': 'एसएमएस पुनः भेजें',
      'whatsapp_otp': 'व्हाट्सएप के जरिए ओटीपी पाएं',
      'verify_continue': 'सत्यापित करें और आगे बढ़ें',
      'change_phone': 'फ़ोन नंबर बदलें',
      'zero_spam_title': '🔒 शून्य स्पैम और डेटा सुरक्षा',
      'zero_spam_desc': 'बातचीत के दौरान आपका फ़ोन नंबर पूरी तरह सुरक्षित और मास्क रहेगा।',
      'home_nav': 'होम',
      'bookings_nav': 'मेरी बुकिंग',
      'profile_nav': 'प्रोफ़ाइल',
      'verified_workers_badge': 'प्रमाणित सहकारी कामगार',
      'trust_hero_title': 'भरोसेमंद सहकारी कारीगर बुक करें',
      'trust_hero_sub': 'उचित मजदूरी, प्रमाणित साख और आपके क्षेत्र में सहकारी सेवाएं।',
      'members_online': '142 सदस्य ऑनलाइन',
      'avg_rating': '4.92 / 5 औसत रेटिंग',
      'emergency_title': 'तुरंत मदद चाहिए?',
      'emergency_sub': 'शॉर्ट सर्किट, पाइप फटना या लॉकआउट',
      'emergency_btn': 'आपातकालीन सेवा का अनुरोध करें',
      'coop_services': 'सहकारी सेवाएं',
      'fair_rates': 'उचित दरें',
      'trades_active': '8 ट्रेड सक्रिय',
      'search_placeholder': 'सेवा या समस्या खोजें (उदा. नल, पंखा)',
      'why_sahayak': 'Work Solute सहकारी ही क्यों?',
      'step1_title': 'अपनी समस्या बताएं',
      'step1_sub': 'सटीक विवरण से कारीगर सही उपकरण और स्पेयर पार्ट्स ला सकेंगे।',
      'service_type': 'सेवा प्रकार',
      'add_photos': 'फ़ोटो या वीडियो जोड़ें',
      'step2_title': 'समय और स्थान',
      'asap_option': 'यथाशीघ्र (आपातकालीन)',
      'schedule_option': 'बाद के लिए शेड्यूल करें',
      'select_date': 'तारीख चुनें',
      'available_slots': 'उपलब्ध समय स्लॉट',
      'service_location': 'सेवा का पता',
      'fair_match_guarantee': 'Work Solute निष्पक्ष मिलान गारंटी',
      'continue_to_matching': 'कारीगर मिलान पर आगे बढ़ें',
      'available_workers': 'उपलब्ध सहकारी कारीगर',
      'how_recommended': 'कारीगरों की सिफारिश कैसे की जाती है',
      'booking_confirmed': 'बुकिंग की पुष्टि हो गई',
      'job_otp_label': 'कार्य प्रारंभ सुरक्षा ओटीपी',
      'service_progress': 'सेवा प्रगति ट्रैकर',
      'call_tech': 'कॉल करें',
      'chat_tech': 'इन-ऐप चैट',
      'my_profile_title': 'मेरी प्रोफ़ाइल और सेटिंग्स',
      'profile_sub': 'क्रेडेंशियल्स, पते और प्राथमिकताएं',
      'saved_addresses': 'सहेजे गए पते',
      'app_language': 'ऐप भाषा',
      'notification_prefs': 'सूचना प्राथमिकताएं',
      'civic_guarantee': 'नागरिक गारंटी और सुरक्षा',
      'help_support': 'सहायता और सपोर्ट',
      'log_out': 'लॉग आउट करें',
      'choose_mode': 'सेवा मोड चुनें',
      'choose_mode_sub': 'तुरंत भेजें या शेड्यूल करें',
      'emergency_request': 'आपातकालीन अनुरोध',
      'emergency_sub_short': 'तुरंत मरम्मत, तत्काल सहायता',
      'book_service': 'सेवा बुक करें',
      'book_sub_short': 'निर्धारित समय, प्रमाणित कारीगर',
      'emergency_domains': '🚨 आपातकालीन क्षेत्र',
      'service_domains': '📅 सेवा क्षेत्र',
      'view_all': 'सभी देखें',
      'hello': 'नमस्ते',
      'my_bookings': 'मेरी बुकिंग',
      'bookings_sub': 'विश्वसनीय घरेलू सेवाएं',
      'tab_upcoming': 'आगामी',
      'tab_completed': 'पूर्ण',
      'tab_cancelled': 'रद्द',
      'no_upcoming_bookings': 'कोई आगामी बुकिंग नहीं है',
      'no_completed_bookings': 'कोई पूर्ण बुकिंग नहीं है',
      'no_cancelled_bookings': 'कोई रद्द बुकिंग नहीं है',
      'verify_otp_action': 'सुरक्षा ओटीपी',
      'complete_pay_action': 'भुगतान व पूरा करें',
      'cancel_booking_action': 'रद्द करें',
      'view_details': 'विवरण देखें',
      'book_a_service_now': 'अभी सेवा बुक करें',
      'stat_bookings': 'बुकिंग',
      'stat_completed': 'पूर्ण',
      'stat_addresses': 'पते',
      'verified_citizen': 'सत्यापित नागरिक',
      'primary_contact': 'प्राथमिक संपर्क',
      'invoicing_email': 'इलेक्ट्रॉनिक चालान',
      'verified_label': 'सत्यापित',
      'verified_otp': 'सत्यापित ओटीपी',
      'add_address': 'जोड़ें',
      'default_badge': 'डिफ़ॉल्ट',
      'set_default': 'डिफ़ॉल्ट बनाएं',
      'whatsapp_updates': 'व्हाट्सएप अपडेट',
      'whatsapp_sub': 'कारीगर आगमन की रीयल-टाइम सूचना',
      'sms_otp': 'एसएमएस प्रारंभ ओटीपी',
      'sms_sub': 'काम शुरू करने के लिए सुरक्षा कोड',
      'booking_reminders': 'बुकिंग रिमाइंडर',
      'reminders_sub': 'सेवा से 1 घंटे पहले स्मरण',
      'support_helpline': '24/7 नागरिक हेल्पलाइन',
      'faqs': 'अक्सर पूछे जाने वाले प्रश्न',
      'faqs_sub': 'सहकारी बुकिंग दिशानिर्देश व नीति',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'full_name': 'पूरा नाम',
      'phone_number': 'फ़ोन नंबर',
      'neighborhood': 'इलाका / सोसायटी',
      'save_changes': 'बदलाव सहेजें',
      'cancel': 'रद्द करें',
      'confirm_logout': 'खाते से लॉग आउट करें?',
      'logout_confirm_msg': 'क्या आप निश्चित रूप से साइन आउट करना चाहते हैं?',
      'detect_live_gps': 'लाइव डिवाइस जीपीएस खोजें',
      'detect_live_gps_sub': 'रीयल-टाइम डिवाइस सेंसर स्थान का उपयोग करता है',
      'service_location_title': 'सेवा स्थान',
      'current_location_label': 'वर्तमान स्थान (लाइव जीपीएस)',
      'rapid_dispatch_badge': 'त्वरित सेवा उपलब्ध (<20 मिनट)',
      'zero_commission_title': 'शून्य-कमीशन चार्टर',
      'zero_commission_sub': '100% कमाई सीधे कारीगरों को जाती है',
      'guild_standards_title': 'कारीगर गिल्ड मानक',
      'guild_standards_sub': 'पृष्ठभूमि सत्यापन और कौशल परीक्षण',
      'insurance_title': 'सुरक्षा बीमा कवर',
      'insurance_sub': '₹25,000 तक की सुरक्षा गारंटी',
      'app_version_label': 'Work Solute सहकारी ऐप v2.4.1',
      'app_footer_desc': 'सार्वजनिक मंच · स्थानीय सहकारी नेटवर्क',
      'worker_set_price': 'कारीगर द्वारा तय पारदर्शी दर',
      'no_base_price': 'कारीगर का कस्टम कोटेशन',
      'otp_verification_title': 'ओटीपी सत्यापन',
      'sms_sent_to': 'एसएमएस कोड भेजा गया:',
      'step_security': 'चरण 2 / 2 · खाता सुरक्षा',
      'mobile_number': 'मोबाइल नंबर',
      'otp_sms_sent_desc': 'इस नंबर पर एसएमएस द्वारा ओटीपी भेजा गया है।',
      'secure_pin': 'सुरक्षित पिन',
      'worker_quote': 'कारीगर कोटेशन',
    },
    'ml': {
      'app_title': 'Work Solute കോ-ഓപ്പറേറ്റീവ്',
      'coop_union': 'സഹകരണ യൂണിയൻ',
      'municipal_network': 'പ്രാദേശിക സഹകരണ നെറ്റ്‌വർക്ക് · പൊതു പ്ലാറ്റ്‌ഫോം',
      'select_language': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
      'select_language_subtitle': 'വിശ്വസനീയമായ സേവന ബുക്കിംഗിനും തൊഴിലാളി വിവരങ്ങൾക്കും നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കൂ.',
      'welcome_title': 'Work Solute-ലേക്ക് സ്വാഗതം',
      'welcome_sub': 'കമ്മീഷനില്ലാതെ, ന്യായമായ നിരക്കിൽ നിങ്ങളുടെ സമീപമുള്ള സഹകരണ തൊഴിലാളികളെ ബുക്ക് ചെയ്യൂ.',
      'continue_google': 'Google വഴി തുടരുക',
      'or_use_email': 'അല്ലെങ്കിൽ ഇമെയിൽ ഉപയോഗിക്കുക',
      'email_label': 'ഇമെയിൽ വിലാസം',
      'password_label': 'പാസ്‌വേഡ്',
      'remember_device': 'ഈ ഉപകരണം ഓർക്കുക',
      'forgot_password': 'പാസ്‌വേഡ് മറന്നോ?',
      'sign_in': 'സൈൻ ഇൻ ചെയ്യുക',
      'create_account': 'പുതിയ അക്കൗണ്ട് ഉണ്ടാക്കുക',
      'member_guarantee_title': 'അംഗ സുരക്ഷാ ഗ്യാരണ്ടി',
      'member_guarantee_desc': 'ബ്രോക്കർ കമ്മീഷനില്ല. ഗിൽഡ് നിശ്ചയിച്ച സുതാര്യമായ നിരക്കുകൾ. പോലീസ് പരിശോധിച്ച തൊഴിലാളികൾ.',
      'verify_phone_title': 'ഫോൺ നമ്പർ സ്ഥിരീകരിക്കുക',
      'verify_phone_desc': 'തൊഴിലാളികൾ എത്തുമ്പോൾ നൽകേണ്ട സുരക്ഷിത OTP ലഭിക്കാൻ ഫോൺ നമ്പർ ആവശ്യമാണ്.',
      'enter_otp': '6 അക്ക OTP രേഖപ്പെടുത്തുക',
      'resend_otp_in': 'വീണ്ടും അയക്കാൻ സമയം',
      'resend_sms': 'SMS വീണ്ടും അയക്കുക',
      'whatsapp_otp': 'WhatsApp വഴി OTP നേടുക',
      'verify_continue': 'സ്ഥിരീകരിച്ച് തുടരുക',
      'change_phone': 'ഫോൺ നമ്പർ മാറ്റുക',
      'zero_spam_title': '🔒 സീറോ സ്പാം & ഡാറ്റാ സുരക്ഷ',
      'zero_spam_desc': 'തൊഴിലാളികളുമായി ആശയവിനിമയം നടത്തുമ്പോൾ നമ്പർ മാസ്ക് ചെയ്യപ്പെടും.',
      'home_nav': 'ഹോം',
      'bookings_nav': 'ബുക്കിംഗുകൾ',
      'profile_nav': 'പ്രൊഫൈൽ',
      'verified_workers_badge': 'പരിശോധിച്ചുറപ്പിച്ച തൊഴിലാളികൾ',
      'trust_hero_title': 'വിശ്വസ്തരായ സഹകരണ തൊഴിലാളികളെ ബുക്ക് ചെയ്യുക',
      'trust_hero_sub': 'ന്യായമായ വേതനവും സുതാര്യമായ സേവനങ്ങളും നിങ്ങളുടെ പ്രദേശത്ത്.',
      'members_online': '142 അംഗങ്ങൾ ലഭ്യമാണ്',
      'avg_rating': '4.92 / 5 റേറ്റിംഗ്',
      'emergency_title': 'അടിയന്തിര സഹായം ആവശ്യമുണ്ടോ?',
      'emergency_sub': 'വൈദ്യുതി തകരാർ, പൈപ്പ് പൊട്ടൽ, വാതിൽ ലോക്ക്',
      'emergency_btn': 'അടിയന്തര സേവനം അഭ്യർത്ഥിക്കുക',
      'coop_services': 'സഹകരണ സേവനങ്ങൾ',
      'fair_rates': 'ന്യായമായ നിരക്കുകൾ',
      'trades_active': '8 മേഖലകൾ സജീവം',
      'search_placeholder': 'സേവനം അല്ലെങ്കിൽ തകരാർ തിരയുക (ഉദാ: ടാപ്പ്, ഫാൻ)',
      'why_sahayak': 'എന്തുകൊണ്ട് Work Solute?',
      'step1_title': 'നിങ്ങളുടെ പ്രശ്നം വിവരിക്കുക',
      'step1_sub': 'ശരിയായ വിവരങ്ങൾ തൊഴിലാളികൾക്ക് കൃത്യമായ ഉപകരണങ്ങൾ കൊണ്ടുവരാൻ സഹായിക്കും.',
      'service_type': 'സേവന വിഭാഗം',
      'add_photos': 'ഫോട്ടോയോ വീഡിയോയോ ചേർക്കുക',
      'step2_title': 'സമയവും സ്ഥലവും',
      'asap_option': 'ഉടൻ തന്നെ (അടിയന്തിരം)',
      'schedule_option': 'പിന്നീടത്തേക്ക് ഷെഡ്യൂൾ ചെയ്യുക',
      'select_date': 'തീയതി തിരഞ്ഞെടുക്കുക',
      'available_slots': 'ലഭ്യമായ സമയം',
      'service_location': 'സേവന വിലാസം',
      'fair_match_guarantee': 'Work Solute തുല്യ അവസര ഗ്യാരണ്ടി',
      'continue_to_matching': 'തൊഴിലാളി സെലക്ഷനിലേക്ക് പോകുക',
      'available_workers': 'ലഭ്യമായ തൊഴിലാളികൾ',
      'how_recommended': 'തൊഴിലാളികളെ എങ്ങനെ തിരഞ്ഞെടുക്കുന്നു',
      'booking_confirmed': 'ബുക്കിംഗ് സ്ഥിരീകരിച്ചു',
      'job_otp_label': 'ജോലി ആരംഭ സുരക്ഷാ OTP',
      'service_progress': 'സേവന പുരോഗതി',
      'call_tech': 'വിളിക്കുക',
      'chat_tech': 'ഇൻ-ആപ്പ് ചാറ്റ്',
      'my_profile_title': 'പ്രൊഫൈലും ക്രമീകരണങ്ങളും',
      'profile_sub': 'വിവരങ്ങൾ, വിലാസങ്ങൾ, ക്രമീകരണങ്ങൾ',
      'saved_addresses': 'സൂക്ഷിച്ച വിലാസങ്ങൾ',
      'app_language': 'ആപ്പ് ഭാഷ',
      'notification_prefs': 'അറിയിപ്പ് ക്രമീകരണങ്ങൾ',
      'civic_guarantee': 'സഹകരണ ഗ്യാരണ്ടി & സുരക്ഷ',
      'help_support': 'സഹായവും സപ്പോർട്ടും',
      'log_out': 'ലോഗ് ഔട്ട് ചെയ്യുക',
      'choose_mode': 'സേവന മോഡ് തിരഞ്ഞെടുക്കുക',
      'choose_mode_sub': 'ഉടൻ അയയ്ക്കുക അല്ലെങ്കിൽ ഷെഡ്യൂൾ ചെയ്യുക',
      'emergency_request': 'അടിയന്തര അഭ്യർത്ഥന',
      'emergency_sub_short': 'അടിയന്തര അറ്റകുറ്റം, ഉടൻ സഹായം',
      'book_service': 'സേവനം ബുക്ക് ചെയ്യുക',
      'book_sub_short': 'ഷെഡ്യൂൾ ചെയ്ത സമയം, സ്ഥിരീകരിച്ച തൊഴിലാളികൾ',
      'emergency_domains': '🚨 അടിയന്തര മേഖലകൾ',
      'service_domains': '📅 സേവന മേഖലകൾ',
      'view_all': 'എല്ലാം കാണുക',
      'hello': 'ഹലോ',
      'my_bookings': 'എന്റെ ബുക്കിംഗുകൾ',
      'bookings_sub': 'സുരക്ഷിത വീട്ടു സേവനങ്ങൾ',
      'tab_upcoming': 'വരാനിരിക്കുന്നവ',
      'tab_completed': 'പൂർത്തിയായവ',
      'tab_cancelled': 'റദ്ദാക്കിയവ',
      'no_upcoming_bookings': 'വരാനിരിക്കുന്ന ബുക്കിംഗുകൾ ഇല്ല',
      'no_completed_bookings': 'പൂർത്തിയായ ബുക്കിംഗുകൾ ഇല്ല',
      'no_cancelled_bookings': 'റദ്ദാക്കിയ ബുക്കിംഗുകൾ ഇല്ല',
      'verify_otp_action': 'സുരക്ഷാ ഒ.ടി.പി',
      'complete_pay_action': 'പണം നൽകുക',
      'cancel_booking_action': 'റദ്ദാക്കുക',
      'view_details': 'വിശദാംശങ്ങൾ കാണുക',
      'book_a_service_now': 'ഇപ്പോൾ ബുക്ക് ചെയ്യുക',
      'stat_bookings': 'ബുക്കിംഗുകൾ',
      'stat_completed': 'പൂർത്തിയായവ',
      'stat_addresses': 'വിലാസങ്ങൾ',
      'verified_citizen': 'സ്ഥിരീകരിച്ച ഉപയോക്താവ്',
      'primary_contact': 'പ്രധാന കോൺടാക്റ്റ് നമ്പർ',
      'invoicing_email': 'ഇൻവോയ്സ് ഇമെയിൽ',
      'verified_label': 'പരിശോധിച്ചു',
      'verified_otp': 'പരിശോധിച്ച OTP',
      'add_address': 'ചേർക്കുക',
      'default_badge': 'ഡിഫോൾട്ട്',
      'set_default': 'ഡിഫോൾട്ടാക്കുക',
      'whatsapp_updates': 'വാട്സ്ആപ്പ് അപ്ഡേറ്റുകൾ',
      'whatsapp_sub': 'തത്സമയ റൂട്ട് വിവരങ്ങൾ',
      'sms_otp': 'എസ്.എം.എസ് ജോലി ആരംഭ OTP',
      'sms_sub': 'സുരക്ഷിത ഡോർസ്റ്റെപ്പ് കോഡ്',
      'booking_reminders': 'ബുക്കിംഗ് ഓർമ്മപ്പെടുത്തലുകൾ',
      'reminders_sub': 'സേവനത്തിന് 1 മണിക്കൂർ മുൻപ്',
      'support_helpline': '24/7 സഹായ ലൈൻ',
      'faqs': 'പതിവുചോദ്യങ്ങൾ',
      'faqs_sub': 'മാർഗ്ഗനിർദ്ദേശങ്ങളും സഹായവും',
      'edit_profile': 'പ്രൊഫൈൽ മാറ്റുക',
      'full_name': 'പൂർണ്ണ പേര്',
      'phone_number': 'ഫോൺ നമ്പർ',
      'neighborhood': 'പ്രദേശം / റെസിഡൻസ്',
      'save_changes': 'മാറ്റങ്ങൾ സൂക്ഷിക്കുക',
      'cancel': 'റദ്ദാക്കുക',
      'confirm_logout': 'ലോഗ് ഔട്ട് ചെയ്യണോ?',
      'logout_confirm_msg': 'തീർച്ചയായും സൈൻ ഔട്ട് ചെയ്യണോ?',
      'detect_live_gps': 'ലൈവ് ജി.പി.എസ് കണ്ടെത്തുക',
      'detect_live_gps_sub': 'ഉപകരണ സെൻസർ ഉപയോഗിക്കുന്നു',
      'service_location_title': 'സേവന സ്ഥലം',
      'current_location_label': 'നിലവിലെ സ്ഥലം (ലൈവ് ജി.പി.എസ്)',
      'rapid_dispatch_badge': 'വേഗത്തിലുള്ള സേവനം (<20 മിനിറ്റ്)',
      'zero_commission_title': 'സീറോ-കമ്മീഷൻ ചാർട്ടർ',
      'zero_commission_sub': '100% തുകയും തൊഴിലാളികൾക്ക് ലഭിക്കുന്നു',
      'guild_standards_title': 'തൊഴിലാളി യൂണിയൻ മാനദണ്ഡങ്ങൾ',
      'guild_standards_sub': 'യോഗ്യതാ പരിശോധന പൂർത്തിയായവർ',
      'insurance_title': 'സുരക്ഷാ ഇൻഷുറൻസ് പരിരക്ഷ',
      'insurance_sub': '₹25,000 വരെയുള്ള പരിരക്ഷ',
      'app_version_label': 'Work Solute കോ-ഓപ്പറേറ്റീവ് ആപ്പ് v2.4.1',
      'app_footer_desc': 'പൊതു പ്ലാറ്റ്‌ഫോം · പ്രാദേശിക സഹകരണ ശൃംഖല',
      'worker_set_price': 'തൊഴിലാളി നിശ്ചയിച്ച നിരക്ക്',
      'no_base_price': 'തൊഴിലാളി ക്വട്ടേഷൻ',
      'otp_verification_title': 'ഒ.ടി.പി പരിശോധന',
      'sms_sent_to': 'എസ്.എം.എസ് കോഡ് അയച്ചു:',
      'step_security': 'ഘട്ടം 2 / 2 · അക്കൗണ്ട് സുരക്ഷ',
      'mobile_number': 'മൊബൈൽ നമ്പർ',
      'otp_sms_sent_desc': 'ഈ നമ്പറിലേക്ക് എസ്.എം.എസ് വഴി ഒ.ടി.പി അയച്ചിട്ടുണ്ട്.',
      'secure_pin': 'സുരക്ഷിത പിൻ',
      'worker_quote': 'തൊഴിലാളി ക്വട്ടേഷൻ',
    },
  };

  String get(String key) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
